// Account error code
const ACCOUNT_ERROR_NOT_FOUND = "ERROR_ACCOUNT_000";
const ACCOUNT_ERROR_EMAIL_EXISTED = "ERROR_ACCOUNT_001";

// Major error code
const MAJOR_ERROR_NOT_FOUND = "ERROR_MAJOR_000";
const MAJOR_ERROR_ID_EXISTED = "ERROR_MAJOR_001";

// Lecturer error code
const LECTURER_ERROR_NOT_FOUND = "ERROR_LECTURER_000";
const LECTURER_ERROR_LECTURER_ID_EXISTED = "ERROR_LECTURER_001";

// Topic error code
const TOPIC_ERROR_NOT_FOUND = "ERROR_TOPIC_000";
const TOPIC_ERROR_ID_EXISTED = "ERROR_TOPIC_001";

module.exports = {
  ACCOUNT_ERROR_NOT_FOUND,
  ACCOUNT_ERROR_EMAIL_EXISTED,
  MAJOR_ERROR_ID_EXISTED,
  MAJOR_ERROR_NOT_FOUND,
  LECTURER_ERROR_NOT_FOUND,
  LECTURER_ERROR_LECTURER_ID_EXISTED,
  TOPIC_ERROR_ID_EXISTED,
  TOPIC_ERROR_NOT_FOUND,
};
