// Account error code
const ACCOUNT_ERROR_NOT_FOUND = "ERR_ACCOUNT_000";
const ACCOUNT_ERROR_EMAIL_EXISTED = "ERR_ACCOUNT_001";

module.exports = { ACCOUNT_ERROR_NOT_FOUND, ACCOUNT_ERROR_EMAIL_EXISTED };
